### ISSUE TITLE
Release v0.1.4 on operatorhub.io

### ISSUE THREAD

**Issue by rsrchboy** [composable-operator/composable#98]
I see v0.1.4 has been tagged, but only v0.1.3 is available out of the operatorhub.io catalog.  (Unless I'm looking at the wrong place.)

Could we update, please?  Or should I be looking for this somewhere else?

Thanks!

https://operatorhub.io/operator/composable-operator

**Comment by xvzf** [comment]
Hey

We switched to GitHub releases for now https://github.com/composable-operator/composable/releases/tag/v0.2.1. For Operator-Hub, I'll have a look in the coming weeks

**Comment by lhriley** [comment]
xpost: https://github.com/composable-operator/composable/issues/100#issuecomment-1444605925

**Comment by xvzf** [comment]
For now, there will not be any releases to operatorhub after migrating out of IBM
